//#define REF_LANG_CN // ChineseSimplified 
//#define REF_LANG_TW // Chinese 
//#define REF_LANG_JP // Japanese

#define REF_LANG_REFRAMEWORK "-v1.5"
#if defined REF_LANG_CN
#define REF_LANG_ENABLED "启用"
#define REF_LANG_DISABLED "禁用"
#define REF_LANG_ABOUT "关于"
#define REF_LANG_LICENSES "许可"
#define REF_LANG_CONFIGURATION "配置"
#define REF_LANG_PERFORMANCE "数据"
#define REF_LANG_VR "虚拟设备"
#define REF_LANG_CAMERA "相机"
#define REF_LANG_GRAPHICS "图形"
#define REF_LANG_FREECAM "视角"
#define REF_LANG_SCENE "场景"
#define REF_LANG_MANUALFLASHLIGHT "手电筒"
#define REF_LANG_FIRSTPERSON "第一人称"
#define REF_LANG_DEVELOPERTOOLS "开发者工具"
#define		REF_LANG_CHAINVIEWER "项目链"
#define		REF_LANG_GAMEOBJECTSDISPLAY "游戏世界"
#define		REF_LANG_OBJECTEXPLORER "对象浏览器"
#define			REF_LANG_SINGLETONS "实例"
#define			REF_LANG_NATIVESINGLETONS "本地实例"
#define			REF_LANG_RENDERER "渲染"
#define			REF_LANG_TYPES "类型"
#define REF_LANG_PLUGINLOADER "插件"
#define REF_LANG_SCRIPTUI "脚本控制台"
#define REF_LANG_SCRIPTRUNNER "脚本"
#elif defined REF_LANG_TW
#define REF_LANG_ENABLED "啟用"
#define REF_LANG_DISABLED "禁用"
#define REF_LANG_ABOUT "關於"
#define REF_LANG_LICENSES "許可"
#define REF_LANG_CONFIGURATION "配置"
#define REF_LANG_PERFORMANCE "數據"
#define REF_LANG_VR "虛擬設備"
#define REF_LANG_CAMERA "相機"
#define REF_LANG_GRAPHICS "圖形"
#define REF_LANG_FREECAM "視角"
#define REF_LANG_SCENE "場景"
#define REF_LANG_MANUALFLASHLIGHT "手電筒"
#define REF_LANG_FIRSTPERSON "第一人稱"
#define REF_LANG_DEVELOPERTOOLS "開發者工具"
#define		REF_LANG_CHAINVIEWER "項目鏈"
#define		REF_LANG_GAMEOBJECTSDISPLAY "遊戲世界"
#define		REF_LANG_OBJECTEXPLORER "對象瀏覽器"
#define			REF_LANG_SINGLETONS "實例"
#define			REF_LANG_NATIVESINGLETONS "本地實例"
#define			REF_LANG_RENDERER "渲染"
#define			REF_LANG_TYPES "類型"
#define REF_LANG_PLUGINLOADER "插件"
#define REF_LANG_SCRIPTUI "腳本控製臺"
#define REF_LANG_SCRIPTRUNNER "腳本"
#elif defined REF_LANG_JP
#define REF_LANG_ENABLED "有効"
#define REF_LANG_DISABLED "無効"
#define REF_LANG_ABOUT "概要"
#define REF_LANG_LICENSES "ライセンス"
#define REF_LANG_CONFIGURATION "構成"
#define REF_LANG_PERFORMANCE "データ"
#define REF_LANG_VR "仮想デバイス"
#define REF_LANG_CAMERA "カメラ"
#define REF_LANG_GRAPHICS "グラフィックス"
#define REF_LANG_FREECAM "ビューポイント"
#define REF_LANG_SCENE "シーン"
#define REF_LANG_MANUALFLASHLIGHT "懐中電灯"
#define REF_LANG_FIRSTPERSON "一人称"
#define REF_LANG_DEVELOPERTOOLS "開発者ツール"
#define		REF_LANG_CHAINVIEWER "アイテムチェーン"
#define		REF_LANG_GAMEOBJECTSDISPLAY "ゲーム ワールド"
#define		REF_LANG_OBJECTEXPLORER "オブジェクト エクスプローラー"
#define			REF_LANG_SINGLETONS "インスタンス"
#define			REF_LANG_NATIVESINGLETONS "ネイティブ インスタンス"
#define			REF_LANG_RENDERER "レンダラー"
#define			REF_LANG_TYPES "タイプ"
#define REF_LANG_PLUGINLOADER "プラグイン"
#define REF_LANG_SCRIPTUI "スクリプト UI"
#define REF_LANG_SCRIPTRUNNER "スクリプト"
#else
#define REF_LANG_ENABLED "Enabled"
#define REF_LANG_DISABLED "Disabled"
#define REF_LANG_ABOUT  ""
#define REF_LANG_LICENSES  ""
#define REF_LANG_CONFIGURATION  ""
#define REF_LANG_PERFORMANCE  ""
#define REF_LANG_VR  ""
#define REF_LANG_CAMERA  ""
#define REF_LANG_GRAPHICS  ""
#define REF_LANG_FREECAM  ""
#define REF_LANG_SCENE  ""
#define REF_LANG_MANUALFLASHLIGHT  ""
#define REF_LANG_FIRSTPERSON  ""
#define REF_LANG_DEVELOPERTOOLS  ""
#define REF_LANG_CHAINVIEWER  ""
#define REF_LANG_GAMEOBJECTSDISPLAY  ""
#define REF_LANG_OBJECTEXPLORER  ""
#define REF_LANG_SINGLETONS  ""
#define REF_LANG_NATIVESINGLETONS  ""
#define REF_LANG_RENDERER  ""
#define REF_LANG_TYPES  ""
#define REF_LANG_PLUGINLOADER  ""
#define REF_LANG_SCRIPTUI  ""
#define REF_LANG_SCRIPTRUNNER  ""
#endif